knp_gaufrette:
    adapters:
        vs_application_profile:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.profile%"
                create: true
        vs_application_filemanager:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.filemanager%"
                create: true
        vs_application_app_pictures:
            local:
                directory: "%vs_application.filemanager_shared_media_gaufrette.app_pictures%"
    filesystems:
        vs_application_profile:
            adapter: "%vs_cms.gaufrette.profile.filesystem%"
        vs_application_filemanager:
            adapter: "%vs_cms.gaufrette.filemanager.filesystem%"
        vs_application_app_pictures:
            adapter: "%vs_application.gaufrette.app_pictures.filesystem%"
