vs_payment:
    resources:
        gateway_config:
            classes:
                model: App\Entity\Payment\GatewayConfig
        payment_method:
            classes:
                model: App\Entity\Payment\PaymentMethod
        payment:
            classes:
                model: App\Entity\Payment\Payment
        order:
            classes:
                model: App\Entity\Payment\Order
        order_item:
            classes:
                model: App\Entity\Payment\OrderItem
        token:
            classes:
                model: App\Entity\Payment\Token
