# vs_api_platform:
#     resource: "@VSApiBundle/Resources/config/routing/api_platform.yaml"
#     prefix:   /
# 
# vs_api_users:
#     resource: "@VSApiBundle/Resources/config/routing/api.yaml"
#     prefix:   /
# 
# vs_api_test_index:
#     path: /api/test-index
#     controller: App\Controller\Api\TestController::index

