vs_payment_shopping_cart:
    resource: "@VSPaymentBundle/Resources/config/routing/shopping_cart.yaml"
    prefix: /

vs_payment_checkout:
    resource: "@VSPaymentBundle/Resources/config/routing/checkout.yaml"
    prefix: /
