stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    persist_default_translation: true
    orm:
        default:
            timestampable:  true
            sluggable:      true
            tree:           true
            translatable:   true
            loggable:       true
            sortable:       true
            
            #blameable:      false
            #uploadable:     false
    class:
        loggable:       Vankosoft\ApplicationBundle\EventSubscriber\LoggableListener
 